language: nix
sudo: true

env:
  # The minimum required plus the latest from each major release plus the next
  # release.
  - EMACS_CI=emacs-25-1
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - sudo apt-get install golang
  - go get -u github.com/vbatts/git-validation

script:
  - make ci
